# Generated by Django 5.1.6 on 2025-04-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimo', '0003_gerentemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradormodel',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
