# Generated by Django 5.1.6 on 2025-04-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimo', '0004_alter_colaboradormodel_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradormodel',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
