# Generated by Django 5.1.6 on 2025-04-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimo', '0005_alter_colaboradormodel_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPIModel',
            fields=[
                ('idEPI', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('quantidade_total', models.IntegerField()),
                ('quantidade_disponivel', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.CreateModel(
            name='EmprestimoModel',
            fields=[
                ('idEMPRESTIMO', models.AutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao_real', models.DateField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Atrasado', 'Atrasado'), ('Devolvido', 'Devolvido')], default='Pendente', max_length=20)),
                ('observacao', models.TextField(null=True)),
                ('idCOLABORADOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_emprestimo.colaboradormodel')),
                ('idEPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_emprestimo.epimodel')),
            ],
        ),
    ]
