# Generated by Django 5.1.6 on 2025-04-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimo', '0006_epimodel_alter_colaboradormodel_cpf_emprestimomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epimodel',
            name='quantidade_disponivel',
        ),
    ]
