# Generated by Django 5.1.6 on 2025-04-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimo', '0007_remove_epimodel_quantidade_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimomodel',
            name='data_devolucao_real',
        ),
    ]
